Controllers/FeedbackController.cs
using BethaniePieShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

public class FeedbackController : Controller
{
    private readonly IFeedbackRepository _feedbackRepository;
    
    public FeedbackController(IFeedbackRepository feedbackRepository)
    {
        _feedbackRepository = feedbackRepository;
    }

    public IActionResult Index()
    {
        return View();
    }


    [HttpPost]
    public IActionResult Index(Feedback model)
    {
        try
        {
            if(ModelState.IsValid)
            {
                _feedbackRepository.Add(model);
                return RedirectToAction("FeedbackComplete");
            }   
            return View(model);
        }
        catch (System.Exception)
        {
            return BadRequest();
        }
    }

    public IActionResult FeedbackComplete()
    {
        return View();
    }

}

Controllers/PieController.cs
using BethaniePieShop.Models;
using BethaniePieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

public class PieController : Controller
{
    private readonly IPieRepository _pieRepository;
    public PieController(IPieRepository pieRepository)
    {
        _pieRepository = pieRepository;
    }

    public IActionResult Index()
    {
        var model = new PieViewModel();
        model.Title = "Welcome to Bethany's Pie Shop";
        var pies = _pieRepository.GetAll();
        model.Pies = pies;

        return View(model);
    }

    public IActionResult Details(int id)
    {
        var pie = _pieRepository.Get(id);
        if (pie == null)
        {
            return NotFound();
        }
        return View(pie);
    }


}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>

@inject SignInManager<IdentityUser> SignInManager
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>
            @ViewBag.Title
        </title>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="~/content/site.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    </head>
    <body> 
       <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
           <!-- Brand and toggle get grouped for better mobile display -->
           <div class="navbar-header">
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                   <span class="sr-only">Toggle navigation</span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
               </button>
               <!-- <a class="navbar-brand" href="#">Title</a> -->
           </div>
       
           <!-- Collect the nav links, forms, and other content for toggling -->
           <div class="collapse navbar-collapse navbar-ex1-collapse">
               <div class="container">
                   <ul class="nav navbar-nav">
                   <li class="active">
                       <a asp-controller="Pie" asp-action="Index" class="navbar-brand">Home</a>
                    </li>
                    <li>                       
                        <a asp-controller="Feedback" asp-action="Index" class="navbar-brand">Feedback</a>
                    </li>
               </ul>

                @if(SignInManager.IsSignedIn(User))
                {
                    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm" method="POST" class="navbar-right">
                        <ul class="nav navbar-nav navbar-right">
                            <li>                       
                                <a href="javascript:document.getElementById('logoutForm').submit()" class="navbar-right">Log off</a>
                            </li>
                        </ul>
                    </form>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                            <li>                       
                                <a asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li>                       
                                <a asp-controller="Account" asp-action="Login">Log in</a>
                            </li>
                    </ul>
                }
               </div>
               <!-- <form class="navbar-form navbar-left" role="search">
                   <div class="form-group">
                       <input type="text" class="form-control" placeholder="Search">
                   </div>
                   <button type="submit" class="btn btn-default">Submit</button>
               </form> -->
               <!-- <ul class="nav navbar-nav navbar-right">
                   <li><a href="#">Link</a></li>
                   <li class="dropdown">
                       <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                       <ul class="dropdown-menu">
                           <li><a href="#">Action</a></li>
                           <li><a href="#">Another action</a></li>
                           <li><a href="#">Something else here</a></li>
                           <li><a href="#">Separated link</a></li>
                       </ul>
                   </li>
               </ul> -->
           </div>
       </nav>
       <div class="container body-content">
            <div class="row">
                @RenderBody()
            </div>
        </div>
    </body>
</html>